
package co.edu.konradlorenz.model.enums;


public enum Dependencia {
    ADMINISTRATIVOS,VENTAS, OPERACIONES, RECURSOS_HUMANOS, FINANZAS, SEGURIDAD, ALMACEN, TECNOLOGIA, ATENCION_A_CLIENTES, LIMPIEZA, LOGISTICA, COMPRAS, CREDITOS_Y_COBRANZAS
}
