
package co.edu.konradlorenz.model.enums;


public enum Cargo {
    GERENTE_GENERAL,
    SUBGERENTE,
    JEFE_DE_OPERACIONES,
    JEFE_DE_RECURSOS_HUMANOS,
    JEFE_DE_FINANZAS,
    JEFE_DE_MARKETING,
    SUPERVISOR_DE_PISO,
    JEFE_DE_ALMACEN,
    REPOSITOR,
    JEFE_DE_SEGURIDAD,
    GUARDIA_DE_SEGURIDAD,
    CAJERO,
    PERSONAL_DE_LIMPIEZA,
    SERVICIO_AL_CLIENTE,
    RESPONSABLE_DE_TECNOLOGIA,
    TECNICO_DE_MANTENIMIENTO,
    ESPECIALISTA_EN_PRODUCTOS_PERECEDEROS,
    COMPRADOR,
    CONTADOR,
    ASISTENTE_CONTABLE
}
