
package co.edu.konradlorenz.model.enums;


public enum TipoProveedor {
    ALIMENTOS_FRESCOS, ALIMENTOS_PROCESADOS, BEBIDAS, PRODUCTOS_LIMPIEZA_Y_HOGAR, PRODUCTOS_CUIDADO_PERSONAL, PRODUCTOS_CONGELADOS, PRODUCTOS_ORGANICOS_O_ESPECIALES, TECNOLOGIA, EQUIPOS_Y_MOBILIARIO, SERVICIOS, PRODUCTOS_LOCALES, PRODUCTOS_INTERNACIONALES, OTROS
}
