/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2024-11-19 21:42:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>SuperLorenz</title>\n");
      out.write("        <style>\n");
      out.write("            /* CSS Unificado */\n");
      out.write("            * {\n");
      out.write("                margin: 0;\n");
      out.write("                padding: 0;\n");
      out.write("                box-sizing: border-box;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            body {\n");
      out.write("                font-family: Arial, sans-serif;\n");
      out.write("                background-color: #f7f7f7;\n");
      out.write("                color: #333;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            header {\n");
      out.write("                background-color: #B089B6;\n");
      out.write("                padding: 10px;\n");
      out.write("                display: flex;\n");
      out.write("                align-items: center;\n");
      out.write("                justify-content: space-between;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .logo {\n");
      out.write("                display: flex;\n");
      out.write("                align-items: center;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .logo img {\n");
      out.write("                width: 40px;\n");
      out.write("                height: 40px;\n");
      out.write("                margin-right: 10px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .search-bar {\n");
      out.write("                display: flex;\n");
      out.write("                align-items: center;\n");
      out.write("                flex-grow: 1;\n");
      out.write("                margin: 0 20px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .search-bar input[type=\"text\"] {\n");
      out.write("                width: 100%;\n");
      out.write("                padding: 5px;\n");
      out.write("                border-radius: 4px 0 0 4px;\n");
      out.write("                border: 1px solid #ccc;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .search-button {\n");
      out.write("                background-color: #794f7f;\n");
      out.write("                border: none;\n");
      out.write("                padding: 5px 10px;\n");
      out.write("                color: #fff;\n");
      out.write("                font-size: 16px;\n");
      out.write("                cursor: pointer;\n");
      out.write("                border-radius: 0 4px 4px 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            nav .nav-button {\n");
      out.write("                margin-left: 20px;\n");
      out.write("                color: #fff;\n");
      out.write("                background-color: #794f7f;\n");
      out.write("                border: none;\n");
      out.write("                padding: 5px 10px;\n");
      out.write("                border-radius: 4px;\n");
      out.write("                cursor: pointer;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            nav .user-text {\n");
      out.write("                font-weight: bold;\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .carousel {\n");
      out.write("                position: relative;\n");
      out.write("                overflow: hidden;\n");
      out.write("                width: 90%;\n");
      out.write("                height: 300px;\n");
      out.write("                margin: 20px auto;\n");
      out.write("                border-radius: 10px;\n");
      out.write("                background-color: #ffffff;\n");
      out.write("                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .carousel-container {\n");
      out.write("                display: flex;\n");
      out.write("                transition: transform 0.5s ease;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .carousel img {\n");
      out.write("                width: 100%;\n");
      out.write("                height: 300px;\n");
      out.write("                object-fit: cover;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .carousel-button {\n");
      out.write("                position: absolute;\n");
      out.write("                top: 50%;\n");
      out.write("                transform: translateY(-50%);\n");
      out.write("                font-size: 24px;\n");
      out.write("                color: #fff;\n");
      out.write("                background: rgba(0, 0, 0, 0.1);\n");
      out.write("                border: none;\n");
      out.write("                padding: 10px;\n");
      out.write("                cursor: pointer;\n");
      out.write("                border-radius: 50%;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .carousel-button.left {\n");
      out.write("                left: 10px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .carousel-button.right {\n");
      out.write("                right: 10px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .product-grid {\n");
      out.write("                display: grid;\n");
      out.write("                grid-template-columns: repeat(5, 1fr);\n");
      out.write("                gap: 20px;\n");
      out.write("                padding: 20px;\n");
      out.write("                max-width: 90%;\n");
      out.write("                margin: 0 auto;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .product-card {\n");
      out.write("                background-color: #fff;\n");
      out.write("                padding: 15px;\n");
      out.write("                text-align: center;\n");
      out.write("                border: 1px solid #ddd;\n");
      out.write("                border-radius: 8px;\n");
      out.write("                box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .product-image {\n");
      out.write("                width: 100%;\n");
      out.write("                height: 150px;\n");
      out.write("                object-fit: cover;\n");
      out.write("                margin-bottom: 10px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            h3 {\n");
      out.write("                font-size: 16px;\n");
      out.write("                margin-bottom: 5px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            p {\n");
      out.write("                font-size: 14px;\n");
      out.write("                color: #666;\n");
      out.write("                margin-bottom: 10px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .price {\n");
      out.write("                font-size: 18px;\n");
      out.write("                font-weight: bold;\n");
      out.write("                color: #e74c3c;\n");
      out.write("                margin-bottom: 15px;\n");
      out.write("                display: block;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .add-to-cart {\n");
      out.write("                background-color: #794f7f;\n");
      out.write("                color: #fff;\n");
      out.write("                border: none;\n");
      out.write("                padding: 10px 20px;\n");
      out.write("                font-size: 16px;\n");
      out.write("                border-radius: 5px;\n");
      out.write("                cursor: pointer;\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .add-to-cart:hover {\n");
      out.write("                background-color: #794f7f;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <header>\n");
      out.write("            <div class=\"logo\">\n");
      out.write("                <img src=\"imagenes/LogoKonrad.png\" alt=\"SuperLorenz Logo\">\n");
      out.write("                <h1>SuperLorenz</h1>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"search-bar\">\n");
      out.write("                <input type=\"text\" placeholder=\"Buscar producto...\">\n");
      out.write("                <button class=\"search-button\">&#128269;</button>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <nav>\n");
      out.write("                <button class=\"nav-button\" onclick=\"goToCart()\">Carrito</button>\n");
      out.write("                <button class=\"nav-button\" onclick=\"goToEmpleado()\">Empleado</button>\n");
      out.write("                <button class=\"nav-button\" onclick=\"goToProveedor()\">Proveedor</button>\n");
      out.write("                <button class=\"nav-button\" onclick=\"goToLogin()\">Ingresar</button>    \n");
      out.write("\n");
      out.write("            </nav>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <main>\n");
      out.write("            <section class=\"carousel\">\n");
      out.write("                <div class=\"carousel-container\">\n");
      out.write("                    <img src=\"imagenes/carrusel1.png\" alt=\"Imagen Carrusel 1\">\n");
      out.write("                    <img src=\"imagenes/carrusel2.png\" alt=\"Imagen Carrusel 2\">\n");
      out.write("                    <img src=\"imagenes/carrusel3.png\" alt=\"Imagen Carrusel 3\">\n");
      out.write("                    <img src=\"imagenes/carrusel4.png\" alt=\"Imagen Carrusel 4\">\n");
      out.write("                    <img src=\"imagenes/carrusel5.png\" alt=\"Imagen Carrusel 5\">\n");
      out.write("                    <img src=\"imagenes/carrusel6.png\" alt=\"Imagen Carrusel 6\">\n");
      out.write("                    <img src=\"imagenes/carrusel7.png\" alt=\"Imagen Carrusel 7\">\n");
      out.write("                    <img src=\"imagenes/carrusel8.png\" alt=\"Imagen Carrusel 8\">\n");
      out.write("                </div>\n");
      out.write("                <button class=\"carousel-button left\" onclick=\"moveCarousel(-1)\">&#10094;</button>\n");
      out.write("                <button class=\"carousel-button right\" onclick=\"moveCarousel(1)\">&#10095;</button>\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("            <section class=\"product-grid\">\n");
      out.write("                <div class=\"product-card\">\n");
      out.write("                    <img src=\"imagenes/imagen1.png\" alt=\"Producto 1\" class=\"product-image\">\n");
      out.write("                    <h3>Nombre Producto 1</h3>\n");
      out.write("                    <p>DescripciÃ³n breve del producto 1.</p>\n");
      out.write("                    <span class=\"price\">$ 1.988.030</span>\n");
      out.write("                    <button class=\"add-to-cart\">Agregar</button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-card\">\n");
      out.write("                    <img src=\"imagenes/imagen2.png\" alt=\"Producto 2\" class=\"product-image\">\n");
      out.write("                    <h3>Nombre Producto 2</h3>\n");
      out.write("                    <p>DescripciÃ³n breve del producto 2.</p>\n");
      out.write("                    <span class=\"price\">$ 2.099.000</span>\n");
      out.write("                    <button class=\"add-to-cart\">Agregar</button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-card\">\n");
      out.write("                    <img src=\"imagenes/imagen3.png\" alt=\"Producto 3\" class=\"product-image\">\n");
      out.write("                    <h3>Nombre Producto 3</h3>\n");
      out.write("                    <p>DescripciÃ³n breve del producto 3.</p>\n");
      out.write("                    <span class=\"price\">$ 1.750.000</span>\n");
      out.write("                    <button class=\"add-to-cart\">Agregar</button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-card\">\n");
      out.write("                    <img src=\"imagenes/imagen4.png\" alt=\"Producto 4\" class=\"product-image\">\n");
      out.write("                    <h3>Nombre Producto 4</h3>\n");
      out.write("                    <p>DescripciÃ³n breve del producto 4.</p>\n");
      out.write("                    <span class=\"price\">$ 1.600.000</span>\n");
      out.write("                    <button class=\"add-to-cart\">Agregar</button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-card\">\n");
      out.write("                    <img src=\"imagenes/imagen5.png\" alt=\"Producto 5\" class=\"product-image\">\n");
      out.write("                    <h3>Nombre Producto 5</h3>\n");
      out.write("                    <p>DescripciÃ³n breve del producto 5.</p>\n");
      out.write("                    <span class=\"price\">$ 1.550.000</span>\n");
      out.write("                    <button class=\"add-to-cart\">Agregar</button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-card\">\n");
      out.write("                    <img src=\"imagenes/imagen6.png\" alt=\"Producto 6\" class=\"product-image\">\n");
      out.write("                    <h3>Nombre Producto 6</h3>\n");
      out.write("                    <p>DescripciÃ³n breve del producto 6.</p>\n");
      out.write("                    <span class=\"price\">$ 1.499.000</span>\n");
      out.write("                    <button class=\"add-to-cart\">Agregar</button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-card\">\n");
      out.write("                    <img src=\"imagenes/imagen7.png\" alt=\"Producto 7\" class=\"product-image\">\n");
      out.write("                    <h3>Nombre Producto 7</h3>\n");
      out.write("                    <p>DescripciÃ³n breve del producto 7.</p>\n");
      out.write("                    <span class=\"price\">$ 1.250.000</span>\n");
      out.write("                    <button class=\"add-to-cart\">Agregar</button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-card\">\n");
      out.write("                    <img src=\"imagenes/imagen8.png\" alt=\"Producto 8\" class=\"product-image\">\n");
      out.write("                    <h3>Nombre Producto 8</h3>\n");
      out.write("                    <p>DescripciÃ³n breve del producto 8.</p>\n");
      out.write("                    <span class=\"price\">$ 1.200.000</span>\n");
      out.write("                    <button class=\"add-to-cart\">Agregar</button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-card\">\n");
      out.write("                    <img src=\"imagenes/imagen9.png\" alt=\"Producto 9\" class=\"product-image\">\n");
      out.write("                    <h3>Nombre Producto 9</h3>\n");
      out.write("                    <p>DescripciÃ³n breve del producto 9.</p>\n");
      out.write("                    <span class=\"price\">$ 1.100.000</span>\n");
      out.write("                    <button class=\"add-to-cart\">Agregar</button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-card\">\n");
      out.write("                    <img src=\"imagenes/imagen10.png\" alt=\"Producto 10\" class=\"product-image\">\n");
      out.write("                    <h3>Nombre Producto 10</h3>\n");
      out.write("                    <p>DescripciÃ³n breve del producto 10.</p>\n");
      out.write("                    <span class=\"price\">$ 1.050.000</span>\n");
      out.write("                    <button class=\"add-to-cart\">Agregar</button>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("        </main>\n");
      out.write("\n");
      out.write("        <script>\n");
      out.write("            // JavaScript Unificado\n");
      out.write("            let currentIndex = 0;\n");
      out.write("\n");
      out.write("            function moveCarousel(direction) {\n");
      out.write("                const carouselContainer = document.querySelector('.carousel-container');\n");
      out.write("                const images = carouselContainer.children;\n");
      out.write("                const totalImages = images.length;\n");
      out.write("\n");
      out.write("                currentIndex = (currentIndex + direction + totalImages) % totalImages;\n");
      out.write("                const offset = -currentIndex * 100;\n");
      out.write("                carouselContainer.style.transform = `translateX(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offset}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("%)`;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function goToCart() {\n");
      out.write("                window.location.href = 'Carrito_de_compras.html';\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function logout() {\n");
      out.write("                window.location.href = 'home.html';\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
